version: '3.9'
services:
    redis:
        container_name: allthingnest-redis
        image: redis
        restart: always
        ports:
            - 6378:6379
        volumes:
            - ./data/redis:/data

volumes:
    data:
